version: '3'
services:
  web:
    image: node-web
    volumes:
      - ./web:/usr/src/app
    working_dir: /usr/src/app
    env_file: .env
    ports:
      - 8995:8995
    build:
      context: .
      dockerfile: web/Dockerfile

  mssql:
    image: mssql-db
    volumes:
      - ./db:/usr/src/app
      - ./mssql:/var/opt/mssql/data
    working_dir: /usr/src/app
    env_file: .env
    ports:
      - 1433:1433
    build:
      context: .
      dockerfile: db/Dockerfile
