version: '3'
services:
  # web server
  web:
    image: node:12.0.0-alpine
    volumes:
      - ./web:/app
    working_dir: /app
    # depends_on:
    #   - mssql
    command: sh -c 'test -d node_modules || npm install; npm run start'
    ports:
      - 8995:8995
    env_file: .env
    build:
      context: .
      dockerfile: Dockerfile

  # MS SQL
  mssql:
    image: mcr.microsoft.com/mssql/server:2017-latest
    container_name: mssql
    command: /bin/sh ./db/entrypoint.sh
    ports:
      - 1433:1433
    env_file: .env
    volumes:
      - dbdata:/var/opt/mssql/data
      - ./mssql/docker-entrypoint.sh:/db/entrypoint.sh
      - ./mssql/docker-init-db.sh:/db/init.sh
      - ./mssql/mssql-cars.sql:/db/init.sql

volumes:
  dbdata: